[project]
name = "arxiv-article-automation"
version = "0.1.0"
description = "Automating collection of articles daily, and creating summaries."
readme = "README.md"
requires-python = ">=3.12"
dependencies = ["requests","beautifulsoup4","arxiv", "tzdata", "lxml", "docling"]

# standard library imports: datetime, typing, zoneinfo, pathlib